#!/usr/bin/env bash
# Guard the output directory before generating into it.
#
# Usage:
#   check-output-dir.sh [OUTPUT_DIR]
#
#   OUTPUT_DIR  where the documents will be written
#               (default docs/review-intelligence)
#
# Every document this skill writes is regenerated and overwritten on each run.
# That is safe in a directory this skill owns and destructive in one a human
# authored, so the two are distinguished by a provenance marker rather than by
# hoping the user picked an empty path.
#
#   no directory            -> create it, write the marker, proceed
#   empty directory         -> write the marker, proceed
#   marker present          -> regeneration, proceed
#   files but no marker     -> refuse (exit 1)
#
# `docs/code-review/` was the original default and is a bad one: 846 public
# repositories already use that path, overwhelmingly for dated point-in-time
# review artifacts that accumulate. This skill's output has the opposite
# lifecycle, so it gets its own directory and checks before writing.

set -euo pipefail

OUTPUT_DIR="${1:-docs/review-intelligence}"
MARKER=".pr-review-intelligence"

write_marker() {
  cat >"$OUTPUT_DIR/$MARKER" <<'MARKERTEXT'
# Generated by the pr-review-intelligence skill.
#
# Every file in this directory is regenerated and OVERWRITTEN on each run.
# Hand edits will be lost. To change the output, change the skill's inputs or
# the review history it mines - not these files.
#
# Delete this marker to make the skill refuse to write here.
MARKERTEXT
}

result() {
  jq -n --arg dir "$OUTPUT_DIR" --arg state "$1" \
    '{output_dir: $dir, state: $state, ok: true}'
}

command -v jq >/dev/null || { echo "error: jq not found on PATH" >&2; exit 2; }

if [ ! -e "$OUTPUT_DIR" ]; then
  mkdir -p "$OUTPUT_DIR"
  write_marker
  echo "==> created ${OUTPUT_DIR}" >&2
  result "created"
  exit 0
fi

if [ ! -d "$OUTPUT_DIR" ]; then
  echo "error: ${OUTPUT_DIR} exists but is not a directory." >&2
  exit 1
fi

if [ -f "$OUTPUT_DIR/$MARKER" ]; then
  echo "==> regenerating ${OUTPUT_DIR}" >&2
  result "regenerate"
  exit 0
fi

# Any entry other than the marker counts as pre-existing content.
existing="$(find "$OUTPUT_DIR" -mindepth 1 -not -name "$MARKER" -print -quit)"

if [ -z "$existing" ]; then
  write_marker
  echo "==> claimed empty ${OUTPUT_DIR}" >&2
  result "claimed-empty"
  exit 0
fi

count="$(find "$OUTPUT_DIR" -mindepth 1 -not -name "$MARKER" -type f | wc -l | tr -d ' ')"

cat >&2 <<EOF
error: ${OUTPUT_DIR} already contains ${count} file(s) and carries no
       pr-review-intelligence marker, so this skill did not create it.

       Everything this skill writes is overwritten on each run. Writing here
       would destroy content it does not own.

       Choose one:
         - point output_dir at a different directory
         - move the existing files elsewhere
         - if this directory really is old output from this skill, run:
             touch ${OUTPUT_DIR}/${MARKER}
EOF
exit 1
